//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rosly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int id { get; set; }
        public System.DateTime timestamp { get; set; }
        public int employee_id { get; set; }
        public int schedule_id { get; set; }
        public Nullable<bool> on_waitlist { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
