//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace Rosly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        [Key]
        public int user_id { get; set; }
        public int notification_id { get; set; }
        public bool is_read { get; set; }
        public Nullable<bool> is_email_sent { get; set; }
        public Nullable<bool> is_email { get; set; }

        public UserNotification()
        {

        }

        public UserNotification(Employee employee, Notification notification, bool isEmailNotification)
        {
            if (employee == null)
                throw new ArgumentNullException("employee");

            if (notification == null)
                throw new ArgumentNullException("notification");

            Employee = employee;
            Notification = notification;
            is_email = isEmailNotification;
        }

        public virtual Employee Employee { get; set; }
        public virtual Notification Notification { get; set; }

    }
}
